# Generated by Django 5.2.10 on 2026-03-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_funcionariocargo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="cargo",
        ),
    ]
