MENU = "Saude"
ICON = "menu"

SUBMENUS = [
    {
        "icon": "dashboard",
        "menu": "Dashboard",
        "role": "view_saude_dashboard",
        "rota": "view_saude_dashboard",
    },
    {
        "add_role": "add_paciente",
        "add_rota": "add_paciente",
        "icon": "list",
        "menu": "Paciente",
        "role": "list_paciente",
        "rota": "list_paciente",
    },
    {
        "add_role": "add_consulta",
        "add_rota": "add_consulta",
        "icon": "list",
        "menu": "Consulta",
        "role": "list_consulta",
        "rota": "list_consulta",
    },
    {
        "add_role": "add_receitamedica",
        "add_rota": "add_receitamedica",
        "icon": "list",
        "menu": "Receitamedica",
        "role": "list_receitamedica",
        "rota": "list_receitamedica",
    },
    {
        "add_role": "add_atestadomedico",
        "add_rota": "add_atestadomedico",
        "icon": "list",
        "menu": "Atestadomedico",
        "role": "list_atestadomedico",
        "rota": "list_atestadomedico",
    },
    {
        "add_role": "add_relatoriomedico",
        "add_rota": "add_relatoriomedico",
        "icon": "list",
        "menu": "Relatoriomedico",
        "role": "list_relatoriomedico",
        "rota": "list_relatoriomedico",
    },
    {
        "add_role": "add_guiatransferencia",
        "add_rota": "add_guiatransferencia",
        "icon": "list",
        "menu": "Guiatransferencia",
        "role": "list_guiatransferencia",
        "rota": "list_guiatransferencia",
    },
    {
        "add_role": "add_pedidoexamemedico",
        "add_rota": "add_pedidoexamemedico",
        "icon": "list",
        "menu": "Pedidoexamemedico",
        "role": "list_pedidoexamemedico",
        "rota": "list_pedidoexamemedico",
    },
    {
        "add_role": "add_dadovital",
        "add_rota": "add_dadovital",
        "icon": "list",
        "menu": "Dadovital",
        "role": "list_dadovital",
        "rota": "list_dadovital",
    },
    {
        "add_role": "add_examemedico",
        "add_rota": "add_examemedico",
        "icon": "list",
        "menu": "Examemedico",
        "role": "list_examemedico",
        "rota": "list_examemedico",
    },
    {
        "add_role": "add_classeexamemedico",
        "add_rota": "add_classeexamemedico",
        "icon": "list",
        "menu": "Classeexamemedico",
        "role": "list_classeexamemedico",
        "rota": "list_classeexamemedico",
    },
    {
        "add_role": "add_tipoexamemedico",
        "add_rota": "add_tipoexamemedico",
        "icon": "list",
        "menu": "Tipoexamemedico",
        "role": "list_tipoexamemedico",
        "rota": "list_tipoexamemedico",
    },
    {
        "add_role": "add_medicamento",
        "add_rota": "add_medicamento",
        "icon": "list",
        "menu": "Medicamento",
        "role": "list_medicamento",
        "rota": "list_medicamento",
    },
    {
        "add_role": "add_medicacaocorrente",
        "add_rota": "add_medicacaocorrente",
        "icon": "list",
        "menu": "Medicacaocorrente",
        "role": "list_medicacaocorrente",
        "rota": "list_medicacaocorrente",
    },
    {
        "add_role": "add_doencacorrente",
        "add_rota": "add_doencacorrente",
        "icon": "list",
        "menu": "Doencacorrente",
        "role": "list_doencacorrente",
        "rota": "list_doencacorrente",
    },
    {
        "add_role": "add_alergiacorrente",
        "add_rota": "add_alergiacorrente",
        "icon": "list",
        "menu": "Alergiacorrente",
        "role": "list_alergiacorrente",
        "rota": "list_alergiacorrente",
    },
]
