# Generated by Django 5.2.10 on 2026-09-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        ("saude", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendas",
                to="hr.employee",
            ),
        ),
    ]
