# Generated by Django 5.2.10 on 2026-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0002_alter_agenda_medico"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="agenda",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="agenda",
            name="service_started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
