# Generated by Django 5.2.10 on 2026-09-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0003_agenda_checked_in_at_agenda_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoexamemedico",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="pedidoexamemedico",
            name="origin",
            field=models.CharField(
                choices=[
                    ("consultation", "Doctor request"),
                    ("direct", "Direct (exam only)"),
                ],
                default="consultation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedidoexamemedico",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos_exames_medicos",
                to="saude.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="pedidoexamemedico",
            name="consulta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos_exames_medicos",
                to="saude.consulta",
            ),
        ),
    ]
