# Generated by Django 5.2.10 on 2026-09-24 15:38

import django.db.models.deletion
import django_resaas.saas.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
        ("saude", "0004_pedidoexamemedico_checked_in_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedidoexamemedico",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itempedidoexamemedico",
            name="rejected_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="itempedidoexamemedico",
            name="rejection_reason",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="resultadoexamemedico",
            name="released",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="resultadoexamemedico",
            name="released_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="resultadoexamemedico",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="itempedidoexamemedico",
            name="estado_exame",
            field=models.CharField(
                choices=[
                    ("pendente", "Pending"),
                    ("agendado", "Scheduled"),
                    ("colhido", "Collected"),
                    ("processamento", "Processing"),
                    ("concluido", "Completed"),
                    ("cancelado", "Cancelled"),
                    ("recolha_necessaria", "Recollection Required"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExamParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("integer", "Integer"),
                            ("text", "Text"),
                            ("boolean", "Yes / No"),
                            ("choice", "Choice"),
                        ],
                        default="decimal",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("choices", models.JSONField(blank=True, default=list)),
                ("patient_visible", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_branch",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entity",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "exame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="saude.examemedico",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Parameter",
                "verbose_name_plural": "Exam Parameters",
                "ordering": ["exame", "order", "name"],
                "unique_together": {("exame", "code")},
            },
            bases=(
                django_resaas.saas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ExamReferenceRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age_min_days", models.PositiveIntegerField(blank=True, null=True)),
                ("age_max_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=150, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_branch",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entity",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="saude.examparameter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Reference Range",
                "verbose_name_plural": "Exam Reference Ranges",
                "ordering": ["parameter", "sex", "age_min_days"],
            },
            bases=(
                django_resaas.saas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ResultParameterValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                    ),
                ),
                ("parameter_code", models.CharField(db_index=True, max_length=50)),
                ("parameter_name", models.CharField(max_length=150)),
                ("data_type", models.CharField(max_length=20)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "reference_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "reference_label",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical_low", "Critical low"),
                            ("critical_high", "Critical high"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_branch",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entity",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="values",
                        to="saude.examparameter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_values",
                        to="saude.resultadoexamemedico",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Parameter Value",
                "verbose_name_plural": "Result Parameter Values",
                "ordering": ["result", "parameter__order", "parameter_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result", "parameter_code"),
                        name="uniq_result_parameter_code",
                    )
                ],
            },
            bases=(
                django_resaas.saas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
