# Generated by Django 5.2.10 on 2026-09-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0006_paciente_portal_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadovital",
            name="agenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dados_vitais",
                to="saude.agenda",
            ),
        ),
        migrations.AddField(
            model_name="dadovital",
            name="glicemia_momento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jejum", "Fasting"),
                    ("pos_prandial", "Postprandial"),
                    ("aleatoria", "Random"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dadovital",
            name="temperatura_local",
            field=models.CharField(
                blank=True,
                choices=[
                    ("axilar", "Axillary"),
                    ("oral", "Oral"),
                    ("timpanica", "Tympanic"),
                    ("retal", "Rectal"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
