# Generated by Django 5.2.10 on 2026-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0007_dadovital_agenda_dadovital_glicemia_momento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="quantidade",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
