# Generated by Django 5.2.10 on 2026-10-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0009_appointmentrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadovital",
            name="frequencia_respiratoria",
            field=models.PositiveIntegerField(blank=True, help_text="rpm", null=True),
        ),
        migrations.AlterField(
            model_name="dadovital",
            name="glicemia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="mmol/L",
                max_digits=5,
                null=True,
            ),
        ),
    ]
