# Generated by Django 5.2.10 on 2026-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0011_exam_parameter_graphable_result_value_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examparameter",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("decimal", "Decimal"),
                    ("integer", "Integer"),
                    ("text", "Text"),
                    ("boolean", "Yes / No"),
                    ("choice", "Choice"),
                    ("date", "Date"),
                ],
                default="decimal",
                max_length=20,
            ),
        ),
    ]
