from saude.models.paciente import Paciente
from saude.models.consulta import Consulta
from saude.models.receitamedica import ReceitaMedica
from saude.models.itemreceita import ItemReceita
from saude.models.atestadomedico import AtestadoMedico
from saude.models.relatoriomedico import RelatorioMedico
from saude.models.guiatransferencia import GuiaTransferencia
from saude.models.pedidoexamemedico import PedidoExameMedico
from saude.models.dadovital import DadoVital
from saude.models.examemedico import ExameMedico
from saude.models.classeexamemedico import ClasseExameMedico
from saude.models.tipoexamemedico import TipoExameMedico
from saude.models.medicamento import Medicamento
from saude.models.medicacaocorrente import MedicacaoCorrente
from saude.models.doencacorrente import DoencaCorrente
from saude.models.alergiacorrente import AlergiaCorrente
