MENU = "Clinica"
ICON = "menu"

SUBMENUS = [
    {
        "icon": "dashboard",
        "menu": "Dashboard",
        "role": "view_clinica_dashboard",
        "rota": "view_clinica_dashboard",
    },
    {
        "add_role": "add_paciente",
        "add_rota": "add_paciente",
        "icon": "people",
        "menu": "Paciente",
        "role": "list_paciente",
        "rota": "list_paciente",
    },
    {
        "add_role": "add_consulta",
        "add_rota": "add_consulta",
        "icon": "home",
        "menu": "Consulta",
        "role": "list_consulta",
        "rota": "list_consulta",
    },
    {
        "add_role": "add_receitamedica",
        "add_rota": "add_receitamedica",
        "icon": "home",
        "menu": "Receita",
        "role": "list_receitamedica",
        "rota": "list_receitamedica",
    },
    {
        "add_role": "add_pedidoexamemedico",
        "add_rota": "add_pedidoexamemedico",
        "icon": "home",
        "menu": "Pedido Exame Medico",
        "role": "list_pedidoexamemedico",
        "rota": "list_pedidoexamemedico",
    },
    {
        "add_role": "add_atestadomedico",
        "add_rota": "add_atestadomedico",
        "icon": "home",
        "menu": "Atestado Medico",
        "role": "list_atestadomedico",
        "rota": "list_atestadomedico",
    },
    {
        "add_role": "add_guiatransferencia",
        "add_rota": "add_guiatransferencia",
        "icon": "home",
        "menu": "Guia Transferencia",
        "role": "list_guiatransferencia",
        "rota": "list_guiatransferencia",
    },
    {
        "add_role": "add_relatoriomedico",
        "add_rota": "add_relatoriomedico",
        "icon": "home",
        "menu": "Relatorio Medico",
        "role": "list_relatoriomedico",
        "rota": "list_relatoriomedico",
    },
    {
        "add_role": "add_internamento",
        "add_rota": "add_internamento",
        "icon": "bed",
        "menu": "Internamento",
        "role": "list_internamento",
        "rota": "list_internamento",
    },
    {
        "add_role": "add_receitamedica",
        "add_rota": "add_receitamedica",
        "icon": "list",
        "menu": "Receitamedica",
        "role": "list_receitamedica",
        "rota": "list_receitamedica",
    },
    {
        "add_role": "add_pedidoexamemedico",
        "add_rota": "add_pedidoexamemedico",
        "icon": "list",
        "menu": "Pedidoexamemedico",
        "role": "list_pedidoexamemedico",
        "rota": "list_pedidoexamemedico",
    },
    {
        "add_role": "add_seguradora",
        "add_rota": "add_seguradora",
        "icon": "list",
        "menu": "Seguradora",
        "role": "list_seguradora",
        "rota": "list_seguradora",
    },
    {
        "add_role": "add_alergiacorrente",
        "add_rota": "add_alergiacorrente",
        "icon": "list",
        "menu": "Alergiacorrente",
        "role": "list_alergiacorrente",
        "rota": "list_alergiacorrente",
    },
]
